import type { ReactNode } from "react";
import { Link } from "react-router-dom";
import { companyName, contactEmail, sitemapLinks } from "../site";

type LegalPageProps = {
  page: "sitemap" | "privacy" | "cookies" | "accessibility";
};

const pageContent = {
  sitemap: {
    kicker: "Sitemap",
    title: "Website sitemap.",
    body: (
      <div className="info-content">
        <p>
          A simple index of the main pages, project routes, and legal information
          available on this website.
        </p>
        <ul className="legal-link-list">
          {sitemapLinks.map((item) => (
            <li key={item.to}>
              <Link className="text-link" to={item.to}>
                {item.label}
              </Link>
            </li>
          ))}
        </ul>
      </div>
    ),
  },
  privacy: {
    kicker: "Privacy policy",
    title: "Privacy policy.",
    body: (
      <div className="info-content">
        <section className="content-section">
          <h2>Who this policy applies to</h2>
          <p>
            This privacy policy explains how {companyName} handles personal
            information submitted through this website, by email, or during early
            project conversations.
          </p>
        </section>

        <section className="content-section">
          <h2>Information collected</h2>
          <p>
            The company only asks for information needed to respond to enquiries,
            discuss possible work, and manage project conversations.
          </p>
          <ul className="content-list">
            <li>Your name and email address.</li>
            <li>Information you include in the contact form or email message.</li>
            <li>Project details, links, files, references, and timeline notes you share.</li>
            <li>Basic technical information generated by normal website use.</li>
          </ul>
        </section>

        <section className="content-section">
          <h2>How information is used</h2>
          <p>
            Personal information is used to reply to enquiries, understand project
            requirements, prepare proposals, deliver agreed work, keep business
            records, and meet legal or accounting obligations.
          </p>
        </section>

        <section className="content-section">
          <h2>Sharing and retention</h2>
          <p>
            Information is not sold. It may be shared with professional advisers,
            service providers, or collaborators where needed to run the business
            or deliver agreed work. Information is kept only for as long as there
            is a business, legal, or administrative reason to retain it.
          </p>
        </section>

        <section className="content-section">
          <h2>Your rights</h2>
          <p>
            You can ask to access, correct, delete, or restrict use of your
            personal information. For privacy questions or deletion requests,
            email{" "}
            <a className="text-link" href={`mailto:${contactEmail}`}>
              {contactEmail}
            </a>
            .
          </p>
        </section>
      </div>
    ),
  },
  cookies: {
    kicker: "Cookie policy",
    title: "Cookie policy.",
    body: (
      <div className="info-content">
        <section className="content-section">
          <h2>What cookies are</h2>
          <p>
            Cookies and similar browser storage technologies are small pieces of
            data saved on your device. They can help a website remember settings,
            keep core functionality working, or understand how the site is used.
          </p>
        </section>

        <section className="content-section">
          <h2>Cookies used on this website</h2>
          <p>
            This website uses a local browser storage item to remember whether
            you have accepted the cookie notice. This prevents the banner from
            appearing repeatedly after you accept it.
          </p>
          <ul className="content-list">
            <li>Name: chris-thomas-cookie-consent.</li>
            <li>Purpose: remembers that the cookie notice has been accepted.</li>
            <li>Duration: remains until you clear this website's data in your browser.</li>
            <li>Type: essential preference storage.</li>
          </ul>
        </section>

        <section className="content-section">
          <h2>Optional cookies</h2>
          <p>
            The site does not currently describe any active analytics or marketing
            cookies. If optional analytics, advertising, or embedded third-party
            services are added later, this page should be updated before those
            tools are enabled.
          </p>
        </section>

        <section className="content-section">
          <h2>Managing cookies</h2>
          <p>
            You can clear or block cookies and local storage through your browser
            settings. Blocking essential storage may mean the cookie banner
            appears again on future visits.
          </p>
        </section>
      </div>
    ),
  },
  accessibility: {
    kicker: "Accessibility statement",
    title: "Accessibility statement.",
    body: (
      <div className="info-content">
        <section className="content-section">
          <h2>Commitment</h2>
          <p>
            {companyName} aims to make this website usable and accessible across
            modern browsers, devices, and assistive technologies.
          </p>
        </section>

        <section className="content-section">
          <h2>What the site should support</h2>
          <ul className="content-list">
            <li>Responsive layouts that work across mobile, tablet, and desktop screens.</li>
            <li>Keyboard access for links, buttons, forms, and navigation.</li>
            <li>Readable contrast, visible focus states, and scalable text.</li>
            <li>Semantic headings, landmarks, labels, and link text where possible.</li>
          </ul>
        </section>

        <section className="content-section">
          <h2>Known limitations</h2>
          <p>
            Some project media and placeholder content may change as the website
            is updated. Accessibility checks should be repeated when final images,
            videos, case studies, or third-party embeds are added.
          </p>
        </section>

        <section className="content-section">
          <h2>Feedback</h2>
          <p>
            If you find an accessibility issue, email{" "}
            <a className="text-link" href={`mailto:${contactEmail}`}>
              {contactEmail}
            </a>{" "}
            with the page address, the device or browser you used, and a short
            description of the problem.
          </p>
        </section>
      </div>
    ),
  },
} satisfies Record<LegalPageProps["page"], {
  kicker: string;
  title: string;
  body: ReactNode;
}>;

export default function LegalPage({ page }: LegalPageProps) {
  const content = pageContent[page];

  return (
    <div className="page-stack">
      <section className="info-page legal-page">
        <div className="intro-main">
          <p className="kicker">{content.kicker}</p>
          <h1>{content.title}</h1>
          {content.body}
        </div>
      </section>
    </div>
  );
}
