import { companyName } from "./site";

export type LegalBlock =
  | {
      type: "paragraph";
      text: string;
    }
  | {
      type: "emailParagraph";
      beforeEmail: string;
      afterEmail: string;
    }
  | {
      type: "list";
      items: string[];
    };

export type LegalPageKey = "privacy" | "cookies";

export type LegalPageContent = {
  title: string;
  sections: Array<{
    heading: string;
    blocks: LegalBlock[];
  }>;
};

export const legalContent = {
  privacy: {
    title: "Privacy policy.",
    sections: [
      {
        heading: "Who this policy applies to.",
        blocks: [
          {
            type: "paragraph",
            text: `This privacy policy explains how ${companyName} handles personal information submitted through this website, by email or during early project conversations.`,
          },
        ],
      },
      {
        heading: "Information collected.",
        blocks: [
          {
            type: "paragraph",
            text: "The company only asks for information needed to respond to enquiries, discuss possible work and manage project conversations.",
          },
          {
            type: "list",
            items: [
              "Your name and email address.",
              "Information you include in the contact form or email message.",
              "Project details, links, files, references and timeline notes you share.",
              "Basic technical information generated by normal website use.",
            ],
          },
        ],
      },
      {
        heading: "How information is used.",
        blocks: [
          {
            type: "paragraph",
            text: "Personal information is used to reply to enquiries, understand project requirements, prepare proposals, deliver agreed work, keep business records and meet legal or accounting obligations.",
          },
        ],
      },
      {
        heading: "Sharing and retention.",
        blocks: [
          {
            type: "paragraph",
            text: "Information is not sold. It may be shared with professional advisers, service providers or collaborators where needed to run the business or deliver agreed work. Information is kept only for as long as there is a business, legal or administrative reason to retain it.",
          },
        ],
      },
      {
        heading: "Your rights.",
        blocks: [
          {
            type: "emailParagraph",
            beforeEmail:
              "You can ask to access, correct, delete or restrict use of your personal information. For privacy questions or deletion requests, email",
            afterEmail: ".",
          },
        ],
      },
    ],
  },
  cookies: {
    title: "Cookie policy.",
    sections: [
      {
        heading: "What cookies are.",
        blocks: [
          {
            type: "paragraph",
            text: "Cookies and similar browser storage technologies are small pieces of data saved on your device. They can help a website remember settings, keep core functionality working or understand how the site is used.",
          },
        ],
      },
      {
        heading: "Cookies used on this website.",
        blocks: [
          {
            type: "paragraph",
            text: "This website uses a local browser storage item to remember whether you have accepted the cookie notice. This prevents the banner from appearing repeatedly after you accept it.",
          },
          {
            type: "list",
            items: [
              "Name: chris-thomas-cookie-consent.",
              "Purpose: remembers that the cookie notice has been accepted.",
              "Duration: remains until you clear this website's data in your browser.",
              "Type: essential preference storage.",
            ],
          },
        ],
      },
      {
        heading: "Optional cookies.",
        blocks: [
          {
            type: "paragraph",
            text: "The site does not currently describe any active analytics or marketing cookies. If optional analytics, advertising or embedded third-party services are added later, this page should be updated before those tools are enabled.",
          },
        ],
      },
      {
        heading: "Managing cookies.",
        blocks: [
          {
            type: "paragraph",
            text: "You can clear or block cookies and local storage through your browser settings. Blocking essential storage may mean the cookie banner appears again on future visits.",
          },
        ],
      },
    ],
  },
} satisfies Record<LegalPageKey, LegalPageContent>;
